### ISSUE TITLE
Indention when adding Custom Effects to Reputation

### ISSUE THREAD

**Issue by dunderbaer** [digitalshadowhawk/pf2e-subsystem-helper#4]
Hi there, I use a custom reward system that gives players a faction boon when they reach a certain milestone (liked, admired, revered) with a faction in my game. I wanted to add those boons to the custom effects using your module, but was only able to input all of it as one big block of text. Do you plan on adding any options to create paragraphs or any formatting options in that text field as well? Would go a long way, allowing me and others to have their Subsystem and any rewards nice and tidy in one place. 

![image](https://github.com/user-attachments/assets/d3e784d8-6a4e-4e79-bec8-21310fca5617)

Currently, I can "only" put the three options in a single block of text, it would be really nice if something like a list or indents after every option was possible.

**Comment by dunderbaer** [comment]
Currently, I can "only" put the three options in a single block of text, it would be really nice if something like a list or indents after every option was possible.

**Comment by digitalshadowhawk** [comment]
I honestly hadn't thought about multi-line, but it should be enough for me to swap the input type=text tag to just the textarea tag. I'll see about adding it to the next release

**Comment by digitalshadowhawk** [comment]
I've changed the text inputs to textarea inputs, the only downside is I haven't been able to get it to recognize new lines unless you actually put <br> (the HTML tag for a new line) in the text you want to have spaced out.
